language: python
install: "pip install --upgrade pip && pip install -r requirements.txt"

# script:
#   - pytest

before_deploy:
  - conda install conda-build
  - conda install anaconda-client
  - bash conda_upload.sh

deploy:
  provider: pypi
  distributions: "sdist bdist_wheel" # Your distributions here
  username: romer8
  password:
    secure: FSSN+q8oXghmRQV0ebC54budQ2JIRRQ0nL9Pia7Xq1OcwwvHzEtrIkMQCaivHJjBb6SJ9YeeMHwBSvikAhghF+pUP2uw6aeZMU49mem7+ozsV4dLud9//lDodyglemJ/OZm6E9UFPmGLxQrk2l+mIoCdn8n/Ke3uZtq6cm5wj5azoAZvrMTvqQFL2saRkBXQ5j6RM7Sy5J+nOQ2zLUehWFQLbzOX7/unY+3KuLhAalrUUPN9BQbjV6VDQk9Da47VHmJTvXnePwhQ9T2buzvNgU4eiisD23KhJtecetJ43HQpqj80p87eSS0OLwAvgnmGDee5tQyCotxfxSr4Gjam6QlYV4LvySS0c6aQ2Iv29cwBC0vm2P3G1nNiaWXFwMdA52KvRfJ6mnCV7L3GlBYf24S+ewEgeIULWxrtyEJ3bIo7Zpj/8x446nuawIwoRsbxG+iJHbU+WZ054YJ2fILqyDVNHCVqCtcTLeRmzVcd8V3qMUCq9DQ1jRcO/M2kHU6SHFMcBpO7hx4CqKdcp4ZMsRamlMJHu5TaYihbGC4itUF/rp0C5Y32qZeKaur8M38/vziQkqn93r1g1XBMbKXmDsSTJm1XYaWd2ryOJQBsJoEW2LEXrhdpnFsicb/cXpoVy4Qn6EsdGc15+4zr6OYhng/OEEFlLQAFpqGJaG8Xx2M=
