language: python
python:
  - "3.6"
install:
  - pip install --upgrade pip && pip install -r requirements.txt
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - conda activate test-environment
  - conda config --add channels conda-forge
  - conda install --file requirements.txt
  - conda config --add channels elkingio
  - conda install conda-build
  - conda build conda.recipe/meta.yaml
  - conda install pywaterml --use-local
  # - python setup.py install

# script:
#   - pytest

before_deploy:
  - conda install conda-build
  - conda install anaconda-client
  - bash conda_upload.sh

deploy:
  provider: pypi
  distributions: "sdist bdist_wheel" # Your distributions here
  username: romer8
  password:
    secure: FSSN+q8oXghmRQV0ebC54budQ2JIRRQ0nL9Pia7Xq1OcwwvHzEtrIkMQCaivHJjBb6SJ9YeeMHwBSvikAhghF+pUP2uw6aeZMU49mem7+ozsV4dLud9//lDodyglemJ/OZm6E9UFPmGLxQrk2l+mIoCdn8n/Ke3uZtq6cm5wj5azoAZvrMTvqQFL2saRkBXQ5j6RM7Sy5J+nOQ2zLUehWFQLbzOX7/unY+3KuLhAalrUUPN9BQbjV6VDQk9Da47VHmJTvXnePwhQ9T2buzvNgU4eiisD23KhJtecetJ43HQpqj80p87eSS0OLwAvgnmGDee5tQyCotxfxSr4Gjam6QlYV4LvySS0c6aQ2Iv29cwBC0vm2P3G1nNiaWXFwMdA52KvRfJ6mnCV7L3GlBYf24S+ewEgeIULWxrtyEJ3bIo7Zpj/8x446nuawIwoRsbxG+iJHbU+WZ054YJ2fILqyDVNHCVqCtcTLeRmzVcd8V3qMUCq9DQ1jRcO/M2kHU6SHFMcBpO7hx4CqKdcp4ZMsRamlMJHu5TaYihbGC4itUF/rp0C5Y32qZeKaur8M38/vziQkqn93r1g1XBMbKXmDsSTJm1XYaWd2ryOJQBsJoEW2LEXrhdpnFsicb/cXpoVy4Qn6EsdGc15+4zr6OYhng/OEEFlLQAFpqGJaG8Xx2M=
