language: python
python:
  - "3.6"
# install:
#   - pip install --upgrade pip && pip install -r requirements.txt
#   - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
#       wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
#     else
#       wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
#     fi
#   - bash miniconda.sh -b -p $HOME/miniconda
#   - source "$HOME/miniconda/etc/profile.d/conda.sh"
#   - hash -r
#   - conda config --set always_yes yes --set changeps1 no
#   - conda update -q conda
#   # Useful for debugging any issues with conda
#   - conda info -a
#   - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
#   - conda activate test-environment
#   - conda config --add channels conda-forge
#   - conda install --file requirements.txt
#   - conda config --add channels elkingio
#   - conda install conda-build
#   - conda config --set anaconda_upload yes
#   - conda build conda.recipe/meta.yaml
#   - conda install python=3.7
#   - conda install pywaterml --use-local

# script:
#   - pytest

deploy:
  provider: pypi
  distributions: "sdist bdist_wheel" # Your distributions here
  username: elkingio
  password:
    secure: p1O0lhmtX4BGvbblah/jozEaCkTyNLgHXPyroe8m3GOPyM/BkbiYOzhpuy+hOAfNTYZ6q2fa1EuS41y/KOxZvg9DRI9uAaVKy4UOMWSTgypfmVVi3QQDj4k2QPcOeV6BmJQ3kaeCxDnnKHPZaNvtczJ7XXtNeFcuEx9BtVYIPrc51/wQLC0ITb/lhtPeGWc43J718alHmUo8PwnrOM1lOc+b1C60wDLtSmza9M2085iTg1ey6sir1BEQyjIqXt0ZnNW3ytffS007u3SBYqUT4g1wmLnU/gKJBdD6ruzTjNZW/g2eGPQ4nG8HDvpkxY4GswuYkj/Wp/pEkmOZEfJiBO4bBhB2qJMlumBn0jlv7c3IeVsAX0xG8Ec3Lb2j8zAmnySoPJqAYqclR59afpOHB4lnRnnvjWc6SKXjeD/ifgrjbTtrd44REGgRQEVTRO5oKovYdtBTyXua7e2tBOqKlocywl//ExCVHI/Pm0ED84nYsDxSZgHEH+pWC0wj0QZk3VtLCPNOwAUNnd0gXzoHJQS7pVj9hKCoXpr/1QT/stNZm+hle4I51t6m0xyiV3oQS03wMsdRPg+ltdLVW/SgCPk4kyZjKI4tojAmjFfWInTJMeIGPG8cGbVsayvVVK8AiiSX8OSRQCEQo4dX5r4y72snvgDwYnOCFblEVnJTAVg=
