{% set name = "pywaterml" %}
# {% set version = "1.1.1" %}

package:
  name: "{{ name|lower }}"
  # version: "{{ version }}"
  version: {{ GIT_DESCRIBE_TAG }}
source:
  # git_url: https://github.com/romer8/pywaterml
  git_url: https://github.com/romer8/pywaterml/releases/download/{{ GIT_DESCRIBE_TAG }}/pywaterml-{{ GIT_DESCRIBE_TAG }}.tar.gz
  sha256: 4642bdee860d3950c33c180a60e3244bc08bbfe13acd86bc278b50e591fc4601

build:
  # number: 0
  number: {{ GIT_DESCRIBE_NUMBER }}
  noarch: python

  # entry_points:
  #   - pywaterml=pywaterml.cli:cli

  # script: python setup.py install
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - numpy
    - owslib
    - pandas
    - pip
    - python
    - suds-py3
    - scikit-learn==0.22
    - tslearn
    - xmltodict
    - cython
  run:
    - numpy
    - owslib
    - pandas
    - python
    - suds-py3
    - scikit-learn==0.22
    - tslearn
    - xmltodict
    - cython

test:
  imports:
    - pywaterml

about:
  home: "https://github.com/romer8/pywaterml"
  license: BSD
  license_family: BSD
  license_file:
  summary: "The pywaterml is a package that lets you handle WaterML functions such as GetValues, GetSitesInfo, etc. In addition it lets offers extra functions such as mean interpolation for data with gaps"
  doc_url: https://pywaterml.readthedocs.io/en/latest/index.html
  dev_url: https://hydroinformatics.byu.edu/

extra:
  recipe-maintainers:
    - romer8
