{% set name = "pywaterml" %}

package:
  name: "{{ name|lower }}"
  version: {{ GIT_DESCRIBE_TAG }}
source:
  git_url: https://github.com/BYU-Hydroinformatics/pywaterml
  sha256: 98326c410a0ceacef8f0cf749815fafebfc47676953290673458c351949331db

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  noarch: python

  script: python setup.py install

requirements:
  host:
    - numpy
    - owslib
    - pandas
    - pip
    - python
    - suds-community
    - tslearn
    - xmltodict
    - cython
  run:
    - numpy
    - owslib
    - pandas
    - python
    - suds-community
    - tslearn
    - xmltodict
    - cython

test:
  imports:
    - pywaterml
    - pywaterml.waterML
    - pywaterml.auxiliaryMod
    - pywaterml.analyzeData
  source_files:
    - tests/test_pywaterml.py
  requires:
    - pytest
  commands:
    - pytest tests/test_pywaterml.py


about:
  home: "https://github.com/romer8/pywaterml"
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: "The pywaterml is a package that lets you handle WaterML functions such as GetValues, GetSitesInfo, etc. In addition it lets offers extra functions such as mean interpolation for data with gaps"
  doc_url: https://pywaterml.readthedocs.io/en/latest/index.html
  dev_url: https://hydroinformatics.byu.edu/

extra:
  recipe-maintainers:
    - romer8
